# Generated by Django 4.2.2 on 2023-07-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_page_is_published_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_in_post_content',
            field=models.BooleanField(default=True, help_text='Este campo precisará estar marcado para exibir a imagem de capa tamém dentro do conteudo do post.'),
        ),
    ]
